#!/bin/bash

set -euo pipefail

project_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
build_dir="$project_dir/build"
host_dir="$HOME/.local/lib/zen-auto-style"
manifest_dir="$HOME/.mozilla/native-messaging-hosts"
hook_dir="$HOME/.config/omarchy/hooks/theme-set.d"
template_dir="$HOME/.config/omarchy/themed"
zen_root="${ZEN_CONFIG_DIR:-$HOME/.config/zen}"
backup_root="$HOME/.local/state/zen-auto-style/backups/$(date +%Y%m%d-%H%M%S-%N)-$$"
available_mods=(
  compact-rounded-content
  flat-sidebar
  sidebar-splitter-hover
  unloaded-tabs
)

"$project_dir/build.sh"

# shellcheck source=/dev/null
source "$build_dir/generated.conf"
native_manifest="$manifest_dir/$NATIVE_HOST_NAME.json"

find_zen_profile() {
  local installs_file="$zen_root/installs.ini"
  local profiles_file="$zen_root/profiles.ini"
  local profile_path

  if [[ -n ${ZEN_PROFILE:-} ]]; then
    printf '%s\n' "$ZEN_PROFILE"
    return
  fi

  if [[ -f $installs_file ]]; then
    profile_path="$(
      awk -F= '
        $1 == "Default" {
          value = substr($0, index($0, "=") + 1)
          if (value != "") {
            print value
            exit
          }
        }
      ' "$installs_file"
    )"
    if [[ -n $profile_path && -d $zen_root/$profile_path ]]; then
      printf '%s\n' "$zen_root/$profile_path"
      return
    fi
  fi

  if [[ -f $profiles_file ]]; then
    profile_path="$(
      awk -F= '
        $1 == "Path" { path = substr($0, index($0, "=") + 1) }
        $1 == "Default" && $2 == "1" && path != "" {
          print path
          exit
        }
      ' "$profiles_file"
    )"
    if [[ -n $profile_path && -d $zen_root/$profile_path ]]; then
      printf '%s\n' "$zen_root/$profile_path"
      return
    fi
  fi

  return 1
}

backup_file() {
  local path=$1

  if [[ -e $path || -L $path ]]; then
    mkdir -p "$backup_root"
    cp -a "$path" "$backup_root/"
  fi
}

ensure_managed_block() {
  local target=$1
  local begin_marker=$2
  local end_marker=$3
  local content=$4
  local temporary

  touch "$target"
  backup_file "$target"
  temporary="$(mktemp)"

  awk \
    -v begin="$begin_marker" \
    -v end="$end_marker" '
      $0 == begin { managed = 1; next }
      $0 == end { managed = 0; next }
      !managed { print }
    ' "$target" >"$temporary"

  {
    printf '%s\n%s\n%s\n\n' "$begin_marker" "$content" "$end_marker"
    cat "$temporary"
  } >"$temporary.new"

  mv "$temporary.new" "$target"
  rm -f "$temporary"
}

remove_legacy_line() {
  local target=$1
  local line=$2
  local temporary

  [[ -f $target ]] || return
  grep -Fqx "$line" "$target" || return 0

  backup_file "$target"
  temporary="$(mktemp)"
  grep -Fvx "$line" "$target" >"$temporary" || true
  mv "$temporary" "$target"
}

mod_is_available() {
  local requested=$1
  local available

  for available in "${available_mods[@]}"; do
    [[ $requested == "$available" ]] && return 0
  done

  return 1
}

selected_mods=()
mods_value="${ZEN_AUTO_STYLE_MODS:-}"
if [[ $mods_value == all ]]; then
  selected_mods=("${available_mods[@]}")
elif [[ -n $mods_value && $mods_value != none ]]; then
  IFS=',' read -r -a selected_mods <<<"$mods_value"
  for mod in "${selected_mods[@]}"; do
    if ! mod_is_available "$mod"; then
      echo "Unknown Zen mod: $mod" >&2
      echo "Available mods: ${available_mods[*]}" >&2
      exit 1
    fi
  done
fi

zen_profile="$(find_zen_profile)" || {
  echo "Unable to find Zen's active profile under $zen_root." >&2
  echo "Start Zen once, or rerun with ZEN_PROFILE=/absolute/profile/path." >&2
  exit 1
}

chrome_dir="$zen_profile/chrome"

mkdir -p \
  "$host_dir" \
  "$manifest_dir" \
  "$hook_dir" \
  "$template_dir" \
  "$chrome_dir"

install -m 755 \
  "$project_dir/native/zen-auto-style-host.py" \
  "$host_dir/zen-auto-style-host.py"
install -m 644 \
  "$build_dir/generated.conf" \
  "$host_dir/generated.conf"

sed \
  -e "s|@HOST_PATH@|$host_dir/zen-auto-style-host.py|g" \
  -e "s|@EXTENSION_ID@|$EXTENSION_ID|g" \
  -e "s|@NATIVE_HOST_NAME@|$NATIVE_HOST_NAME|g" \
  "$project_dir/native/native-host.json.in" \
  >"$native_manifest"

install -m 755 \
  "$project_dir/omarchy/theme-set-hook" \
  "$hook_dir/zen-auto-style"

backup_file "$template_dir/custom-zen.css.tpl"
install -m 644 \
  "$project_dir/assets/omarchy/custom-zen.css.tpl" \
  "$template_dir/custom-zen.css.tpl"

backup_file "$chrome_dir/zen-auto-style-chrome.css"
install -m 644 \
  "$project_dir/assets/zen/zen-auto-style-chrome.css" \
  "$chrome_dir/zen-auto-style-chrome.css"
backup_file "$chrome_dir/zen-auto-style-content.css"
install -m 644 \
  "$project_dir/assets/zen/zen-auto-style-content.css" \
  "$chrome_dir/zen-auto-style-content.css"

mods_dir="$chrome_dir/zen-auto-style-mods"
backup_file "$chrome_dir/zen-auto-style-mods.css"
rm -rf "$mods_dir"
mkdir -p "$mods_dir"

for mod in "${available_mods[@]}"; do
  install -m 644 \
    "$project_dir/assets/zen/mods/$mod.css" \
    "$mods_dir/$mod.css"
done

{
  echo "/* Generated by Zen Auto Style. */"
  for mod in "${selected_mods[@]}"; do
    printf '@import url("zen-auto-style-mods/%s.css");\n' "$mod"
  done
} >"$chrome_dir/zen-auto-style-mods.css"

remove_legacy_line \
  "$chrome_dir/userChrome.css" \
  '@import url("zen-auto-style-chrome.css");'
remove_legacy_line \
  "$chrome_dir/userChrome.css" \
  '@import url("zen-auto-style-mods.css");'
remove_legacy_line \
  "$chrome_dir/userContent.css" \
  '@import url("zen-auto-style-content.css");'

ensure_managed_block \
  "$chrome_dir/userChrome.css" \
  '/* BEGIN ZEN AUTO STYLE */' \
  '/* END ZEN AUTO STYLE */' \
  $'@import url("zen-auto-style-chrome.css");\n@import url("zen-auto-style-mods.css");'
ensure_managed_block \
  "$chrome_dir/userContent.css" \
  '/* BEGIN ZEN AUTO STYLE */' \
  '/* END ZEN AUTO STYLE */' \
  '@import url("zen-auto-style-content.css");'

remove_legacy_line \
  "$zen_profile/user.js" \
  'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'
ensure_managed_block \
  "$zen_profile/user.js" \
  '// BEGIN ZEN AUTO STYLE' \
  '// END ZEN AUTO STYLE' \
  $'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);\nuser_pref("extensions.experiments.enabled", true);\nuser_pref("xpinstall.signatures.required", false);'

backup_file "$chrome_dir/custom-zen.css"

# Resolve the Omarchy theme directory for both 4.x (state) and legacy (config)
if [[ -d "$HOME/.local/state/omarchy/current/theme" ]]; then
  _theme_custom_css="$HOME/.local/state/omarchy/current/theme/custom-zen.css"
elif [[ -d "$HOME/.config/omarchy/current/theme" ]]; then
  _theme_custom_css="$HOME/.config/omarchy/current/theme/custom-zen.css"
else
  _theme_custom_css="$HOME/.local/state/omarchy/current/theme/custom-zen.css"
fi

ln -sfn "$_theme_custom_css" "$chrome_dir/custom-zen.css"

mkdir -p "$HOME/.cache/zen-auto-style"
touch "$HOME/.cache/zen-auto-style/reload"

if command -v omarchy >/dev/null 2>&1; then
  omarchy theme refresh
else
  echo "Warning: omarchy is not on PATH; run 'omarchy theme refresh' later." >&2
fi

echo "Installed Zen CSS into: $zen_profile"
echo "Installed Omarchy template, native host, and theme hook."
echo "Extension ID: $EXTENSION_ID"
echo "Native host: $NATIVE_HOST_NAME"
if (( ${#selected_mods[@]} )); then
  echo "Optional Zen mods: ${selected_mods[*]}"
else
  echo "Optional Zen mods: none (stock themed Zen)"
fi
if [[ -d $backup_root ]]; then
  echo "Backups: $backup_root"
fi
echo "Install build/zen-auto-style.xpi in Zen, then restart Zen once."
